export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";

export const GET_MEMBERS = "GET_MEMBERS";
export const ADD_MEMBER = "ADD_MEMBER";
export const GET_MEMBER = "GET_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const MEMBERS_LOADING = "MEMBERS_LOADING";
export const GET_SEARCH_MEMBERS = "GET_SEARCH_MEMBERS";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";

export const GET_INVOICES = "GET_INVOICES";
export const ADD_INVOICE = "ADD_INVOICE";
export const GET_INVOICE = "GET_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const INVOICES_LOADING = "INVOICES_LOADING";

export const ADD_REDUCER = 'ADD_REDUCER';